name: Build and deploy Python app to Azure Web App - WareHouseAPIS2024

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step 1: Nastavenie Pythonu
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 2: Vytvorenie a aktivácia virtuálneho prostredia
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 3: Inštalácia závislostí
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Spustenie testov
      # - name: Run tests
      #   run: |
      #     pytest

      # Step 4: Vytvorenie zip súboru s aplikáciou pre nasadenie
      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x "venv/*"

      # Step 5: Nahranie artefaktu pre nasadenie
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Step 1: Stiahnutie artefaktu z build jobu
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Rozbalenie artefaktu
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 3: Nasadenie na Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'WareHouseAPIS2024'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_475A7374FE9A4A039877756EC7421C08 }}
